# Generated by Django 5.1.2 on 2024-11-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('std_id', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
